using System.Reflection;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Agility.Management.Sdk.Clients;

namespace Agility.Management.Sdk.Tests;

/// <summary>
/// Checks the SDK against the OpenAPI spec snapshot in <c>spec/</c>: every operation must be called by some SDK
/// method, and every SDK call must be an operation in the spec. The methods are really invoked (against a fake
/// handler), so this checks the routes the code sends, not what it says it sends.
/// </summary>
public partial class SpecCoverageTests
{
    /// <summary>Operations the SDK deliberately doesn't call, and why.</summary>
    private static readonly Dictionary<string, string> Excluded = new()
    {
        ["GET /oauth/authorize"] = "A browser redirect, not an API call: `client.OAuth.GetAuthorizeUri` builds the URL.",
        ["GET /oauth/callback"] = "The API's own redirect target during sign-in; clients don't call it.",
    };

    internal static readonly Type[] ClientTypes =
    [
        typeof(AssetsClient), typeof(BatchesClient), typeof(ContainersClient), typeof(ContentClient),
        typeof(InstanceUsersClient), typeof(LocalesClient), typeof(LocalizationClient), typeof(ModelsClient),
        typeof(OAuthClient), typeof(PagesClient), typeof(PersonalAccessTokensClient), typeof(SyncStatusClient),
        typeof(TypesClient), typeof(UrlRedirectionsClient), typeof(ServerUsersClient), typeof(WebhooksClient),
    ];

    [Fact]
    public async Task Every_spec_operation_is_called_and_every_call_is_in_the_spec()
    {
        var spec = LoadSpecOperations();
        var called = await InvokeEverything();

        var missing = spec.Keys.Except(called.Keys).Except(Excluded.Keys.Select(ExclusionKey)).Order().ToList();
        var unknown = called.Keys.Except(spec.Keys).Order().Select(k => $"{k} (from {string.Join(", ", called[k])})").ToList();
        var staleExclusions = Excluded.Keys.Where(k => !spec.ContainsKey(ExclusionKey(k))).ToList();

        Assert.True(missing.Count == 0, "Spec operations no SDK method calls:\n" + string.Join("\n", missing));
        Assert.True(unknown.Count == 0, "SDK calls that aren't in the spec:\n" + string.Join("\n", unknown));
        Assert.True(staleExclusions.Count == 0, "Exclusions no longer in the spec:\n" + string.Join("\n", staleExclusions));

        CheckCoverageDoc(spec, called);
    }

    private static string ExclusionKey(string op) => op[..op.IndexOf(' ', StringComparison.Ordinal)] + op[op.IndexOf(' ', StringComparison.Ordinal)..].ToLowerInvariant();

    /// <summary>
    /// docs/api-coverage.md maps every operation to its SDK method. It's generated here so it can't drift:
    /// run the tests with AGILITY_UPDATE_DOCS=1 to rewrite it.
    /// </summary>
    private static void CheckCoverageDoc(Dictionary<string, (string Verb, string Route, string Tag)> spec, Dictionary<string, List<string>> called)
    {
        var sb = new System.Text.StringBuilder();
        sb.Append("# API coverage\n\n");
        sb.Append("Every Management API operation in [`spec/management-api.openapi.json`](../spec/management-api.openapi.json) and the SDK method that calls it. ");
        sb.Append("Generated by `SpecCoverageTests`; run `AGILITY_UPDATE_DOCS=1 dotnet test` to update it.\n\n");
        sb.Append(System.Globalization.CultureInfo.InvariantCulture, $"{spec.Count - Excluded.Count} of {spec.Count} operations are covered. Instance routes are relative to `/api/v1/instance/{{guid}}`, and every instance-level method takes the GUID first.\n");
        foreach (var tag in spec.Values.Select(v => v.Tag).Distinct().Order(StringComparer.Ordinal))
        {
            sb.Append(System.Globalization.CultureInfo.InvariantCulture, $"\n## {tag}\n\n| Operation | SDK method |\n|---|---|\n");
            foreach (var (key, op) in spec.Where(kv => kv.Value.Tag == tag).OrderBy(kv => kv.Value.Route, StringComparer.Ordinal).ThenBy(kv => kv.Value.Verb, StringComparer.Ordinal))
            {
                var route = op.Route.Replace("/api/v1/instance/{guid}", "", StringComparison.Ordinal);
                var methods = called.TryGetValue(key, out var m)
                    ? string.Join("<br>", m.Distinct().Select(x => $"`{Accessor(x)}`"))
                    : Excluded.TryGetValue($"{op.Verb} {op.Route}", out var why) ? $"— {why}" : "—";
                sb.Append(System.Globalization.CultureInfo.InvariantCulture, $"| `{op.Verb} {route}` | {methods} |\n");
            }
        }

        var docPath = Path.Combine(RepoRoot(), "docs", "api-coverage.md");
        var expected = sb.ToString();
        if (Environment.GetEnvironmentVariable("AGILITY_UPDATE_DOCS") == "1")
        {
            File.WriteAllText(docPath, expected);
            return;
        }
        var actual = File.Exists(docPath) ? File.ReadAllText(docPath).ReplaceLineEndings("\n") : "";
        Assert.True(actual == expected, "docs/api-coverage.md is out of date: run 'AGILITY_UPDATE_DOCS=1 dotnet test' and commit it.");
    }

    private static string Accessor(string typeAndMethod)
    {
        var (type, method) = (typeAndMethod[..typeAndMethod.IndexOf('.', StringComparison.Ordinal)], typeAndMethod[(typeAndMethod.IndexOf('.', StringComparison.Ordinal) + 1)..]);
        var prefix = type switch
        {

            nameof(OAuthClient) => "client.OAuth",
            nameof(PersonalAccessTokensClient) => "client.PersonalAccessTokens",
            nameof(TypesClient) => "client.Types",
            nameof(ServerUsersClient) => "client.ServerUsers",
            _ => "client." + type.Replace("Client", "", StringComparison.Ordinal),
        };
        return $"{prefix}.{method}";
    }

    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "global.json"))) dir = dir.Parent;
        return dir?.FullName ?? throw new InvalidOperationException("Couldn't find the repository root.");
    }

    [Fact]
    public void The_authorize_URL_matches_the_spec_route()
    {
        using var client = new AgilityManagementClient(new AgilityManagementOptions { AccessToken = "t" });
        var uri = client.OAuth.GetAuthorizeUri(new Uri("https://app.example.com/callback"), state: "xyz");

        Assert.Equal("https://mgmt.aglty.io/oauth/authorize", uri.GetLeftPart(UriPartial.Path));
        Assert.Contains("redirect_uri=https%3A%2F%2Fapp.example.com%2Fcallback", uri.Query, StringComparison.Ordinal);
        Assert.Contains("scope=offline_access", uri.Query, StringComparison.Ordinal);
        Assert.Contains("state=xyz", uri.Query, StringComparison.Ordinal);
    }

    /// <summary>"VERB /path" for every spec operation, with path parameters typed: {int}, {str}, {bool}, {uuid}.</summary>
    private static Dictionary<string, (string Verb, string Route, string Tag)> LoadSpecOperations()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "spec", "management-api.openapi.json");
        var paths = JsonNode.Parse(File.ReadAllText(path))!["paths"]!.AsObject();
        var ops = new Dictionary<string, (string, string, string)>();
        foreach (var (route, item) in paths)
        {
            foreach (var (verb, op) in item!.AsObject())
            {
                if (verb is not ("get" or "post" or "put" or "patch" or "delete")) continue;
                var types = (op!["parameters"] as JsonArray ?? [])
                    .Where(p => p!["in"]!.GetValue<string>() == "path")
                    .ToDictionary(p => p!["name"]!.GetValue<string>(), p => ParameterKind(p!["schema"]));
                var typed = PathParameter().Replace(route, m => types.TryGetValue(m.Groups[1].Value, out var kind) ? kind : "{str}");
                var tag = (op["tags"] as JsonArray)?.FirstOrDefault()?.GetValue<string>() ?? "Other";
                if (!ops.TryAdd($"{verb.ToUpperInvariant()} {typed.ToLowerInvariant()}", (verb.ToUpperInvariant(), route, tag)))
                    throw new InvalidOperationException($"Two spec operations normalize to {verb} {typed}.");
            }
        }
        return ops;
    }

    private static string ParameterKind(JsonNode? schema) =>
        (schema?["type"]?.GetValue<string>(), schema?["format"]?.GetValue<string>()) switch
        {
            ("integer", _) => "{int}",
            ("boolean", _) => "{bool}",
            ("string", "uuid") => "{uuid}",
            _ => "{str}",
        };

    /// <summary>Invokes every public async method once and returns "VERB /normalized/path" → methods that called it.</summary>
    private static async Task<Dictionary<string, List<string>>> InvokeEverything()
    {
        var body = "{}";
        var handler = new FakeHandler(r => r.Method == HttpMethod.Get && BatchPoll().IsMatch(r.Uri.AbsolutePath)
            ? FakeHandler.Json(TestClient.ProcessedBatch(77))
            : body == "<bytes>" ? new HttpResponseMessage(System.Net.HttpStatusCode.OK) { Content = new ByteArrayContent([1, 2, 3]) }
            : FakeHandler.Json(body));
        using var client = TestClient.Create(handler);
        var targets = Targets(client);

        var called = new Dictionary<string, List<string>>();
        foreach (var type in ClientTypes)
        {
            var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
                .Where(m => typeof(Task).IsAssignableFrom(m.ReturnType));
            foreach (var method in methods)
            {
                body = ResponseFor(method.ReturnType);
                var before = handler.Requests.Count;
                var task = (Task)method.Invoke(targets[type], [.. method.GetParameters().Select(DummyValue)])!;
                await task;
                foreach (var request in handler.Requests.Skip(before))
                {
                    // Polling a batch is part of every batch operation, not the method's own route.
                    if (method.Name != nameof(BatchesClient.GetBatchAsync) && method.Name != nameof(BatchesClient.WaitForBatchAsync)
                        && request.Method == HttpMethod.Get && BatchPoll().IsMatch(request.Uri.AbsolutePath))
                        continue;
                    var key = Normalize(request.Method.Method, Uri.UnescapeDataString(request.Uri.AbsolutePath));
                    if (!called.TryGetValue(key, out var list)) called[key] = list = [];
                    list.Add($"{type.Name}.{method.Name}");
                }
                Assert.True(handler.Requests.Count > before, $"{type.Name}.{method.Name} sent no request.");
            }
        }
        return called;
    }

    internal static Dictionary<Type, object> Targets(AgilityManagementClient client) => new()
    {
        [typeof(AssetsClient)] = client.Assets, [typeof(BatchesClient)] = client.Batches,
        [typeof(ContainersClient)] = client.Containers, [typeof(ContentClient)] = client.Content,
        [typeof(InstanceUsersClient)] = client.InstanceUsers, [typeof(LocalesClient)] = client.Locales,
        [typeof(LocalizationClient)] = client.Localization, [typeof(ModelsClient)] = client.Models,
        [typeof(PagesClient)] = client.Pages, [typeof(SyncStatusClient)] = client.SyncStatus,
        [typeof(UrlRedirectionsClient)] = client.UrlRedirections, [typeof(WebhooksClient)] = client.Webhooks,
        [typeof(OAuthClient)] = client.OAuth, [typeof(PersonalAccessTokensClient)] = client.PersonalAccessTokens,
        [typeof(TypesClient)] = client.Types, [typeof(ServerUsersClient)] = client.ServerUsers,
    };

    /// <summary>A response body that deserializes into what the method returns.</summary>
    private static string ResponseFor(Type returnType)
    {
        var result = returnType.IsGenericType ? returnType.GetGenericArguments()[0] : typeof(void);
        if (result == typeof(BatchResult)) return "77";
        if (result == typeof(string)) return "\"key\"";
        if (result == typeof(Stream)) return "<bytes>";
        if (result.IsGenericType && result.GetGenericTypeDefinition() == typeof(List<>)) return "[]";
        return "{}";
    }

    internal static object? DummyValue(ParameterInfo p)
    {
        var t = p.ParameterType;
        if (t == typeof(CancellationToken)) return CancellationToken.None;
        if (t == typeof(string))
            return p.Name switch
            {
                "instanceGuid" => TestClient.InstanceGuid,
                "locale" => "en-us",
                _ => p.Name!.Contains("fileName", StringComparison.Ordinal) ? "f.xlsx" : "ref",
            };
        if (t == typeof(int)) return 5;
        if (t == typeof(bool)) return p.HasDefaultValue ? p.DefaultValue : false;
        if (t == typeof(Guid)) return System.Guid.Parse("11111111-2222-3333-4444-555555555555");
        if (t == typeof(Uri)) return new Uri("https://app.example.com/cb");
        if (t == typeof(Stream)) return new MemoryStream([1, 2, 3]);
        if (t.IsEnum) return Enum.GetValues(t).GetValue(0);
        if (Nullable.GetUnderlyingType(t) is not null) return null;
        if (t == typeof(IEnumerable<int>)) return new[] { 1, 2 };
        if (t == typeof(IReadOnlyCollection<AssetUpload>)) return new[] { new AssetUpload("a.txt", new MemoryStream([1])) };
        if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(IReadOnlyList<>))
            return Array.CreateInstance(t.GetGenericArguments()[0], 0);
        if (t == typeof(Models.CreateBatchWithItemsRequest))
            return new Models.CreateBatchWithItemsRequest
            {
                Operation = Models.WorkflowOperationType.Publish,
                Items = [new Models.AddBatchItemRequest { ItemType = Models.BatchItemType.Page, ItemID = 5 }],
            };
        if (p.HasDefaultValue) return p.DefaultValue;
        return Activator.CreateInstance(t);
    }

    /// <summary>
    /// Types each concrete path segment the way <see cref="LoadSpecOperations"/> types spec parameters. The dummy
    /// values make this unambiguous: strings are "ref", "en-us" or the instance GUID; ints are digits.
    /// </summary>
    private static string Normalize(string verb, string path)
    {
        var segments = path.Trim('/').Split('/').Select(s => s switch
        {
            TestClient.InstanceGuid or "en-us" or "ref" => "{str}",
            "true" or "false" => "{bool}",
            _ when int.TryParse(s, out _) => "{int}",
            _ when System.Guid.TryParse(s, out _) => "{uuid}",
            _ => s.ToLowerInvariant(),
        });
        return $"{verb} /{string.Join('/', segments)}";
    }

    [GeneratedRegex("{([^}]+)}")]
    private static partial Regex PathParameter();

    [GeneratedRegex("/instance/[^/]+/batch/\\d+$")]
    private static partial Regex BatchPoll();
}
