// <auto-generated>
// Generated by tools/GenerateModels.cs from spec/management-api.openapi.json. Do not edit.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

using Agility.Management.Sdk.Models;

namespace Agility.Management.Sdk.Serialization;

/// <summary>
/// Source-generated serialization for every type the SDK sends or receives.
/// </summary>
/// <remarks>
/// Null properties are left out of requests. The API binds a missing property to its default, but it
/// rejects an explicit <c>null</c> for many properties the spec marks nullable ("field is required"), and it
/// treats a sent list as a replacement, so an unset list must never go out as <c>null</c> or <c>[]</c>.
/// Nulls inside a <c>JsonObject</c> (a content item's field values) are data and are still sent.
/// </remarks>
[JsonSourceGenerationOptions(
    PropertyNameCaseInsensitive = true,
    NumberHandling = JsonNumberHandling.AllowReadingFromString,
    AllowTrailingCommas = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(int?))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(JsonNode))]
[JsonSerializable(typeof(List<AssetMedia>))]
[JsonSerializable(typeof(List<ContentContainer>))]
[JsonSerializable(typeof(List<ContentItem>))]
[JsonSerializable(typeof(List<ContentModel>))]
[JsonSerializable(typeof(List<ContentSectionDefinition>))]
[JsonSerializable(typeof(List<InstanceRole>))]
[JsonSerializable(typeof(List<Locale>))]
[JsonSerializable(typeof(List<Notification>))]
[JsonSerializable(typeof(List<PageModel>))]
[JsonSerializable(typeof(List<Sitemap>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<UrlRedirection>))]
[JsonSerializable(typeof(List<WebsiteUser>))]
[JsonSerializable(typeof(AddBatchItemRequest))]
[JsonSerializable(typeof(AllTypesResponse))]
[JsonSerializable(typeof(AssetContainer))]
[JsonSerializable(typeof(AssetGalleries))]
[JsonSerializable(typeof(AssetMedia))]
[JsonSerializable(typeof(AssetMediaGrouping))]
[JsonSerializable(typeof(AssetMediaGroupingMetaData))]
[JsonSerializable(typeof(AssetMediaList))]
[JsonSerializable(typeof(Batch))]
[JsonSerializable(typeof(BatchCreateResult))]
[JsonSerializable(typeof(BatchItem))]
[JsonSerializable(typeof(BatchItemType))]
[JsonSerializable(typeof(BatchOperationType))]
[JsonSerializable(typeof(BatchState))]
[JsonSerializable(typeof(CascadeItem))]
[JsonSerializable(typeof(ContentContainer))]
[JsonSerializable(typeof(ContentContainerPagedResult))]
[JsonSerializable(typeof(ContentItem))]
[JsonSerializable(typeof(ContentItemHistory))]
[JsonSerializable(typeof(ContentItemHistoryResponse))]
[JsonSerializable(typeof(ContentItemProperties))]
[JsonSerializable(typeof(ContentList))]
[JsonSerializable(typeof(ContentListFilterModel))]
[JsonSerializable(typeof(ContentModel))]
[JsonSerializable(typeof(ContentModelField))]
[JsonSerializable(typeof(ContentScripts))]
[JsonSerializable(typeof(ContentSectionDefaultModule))]
[JsonSerializable(typeof(ContentSectionDefinition))]
[JsonSerializable(typeof(ContentViewColumn))]
[JsonSerializable(typeof(ContentViewType))]
[JsonSerializable(typeof(CreateBatchWithItemsRequest))]
[JsonSerializable(typeof(DateRangeFilter))]
[JsonSerializable(typeof(EnumInfo))]
[JsonSerializable(typeof(FieldFilter))]
[JsonSerializable(typeof(FieldFilterValue))]
[JsonSerializable(typeof(InitializeContentListRequest))]
[JsonSerializable(typeof(InitializeContentRequest))]
[JsonSerializable(typeof(InitializePageRequest))]
[JsonSerializable(typeof(InstancePermission))]
[JsonSerializable(typeof(InstanceRole))]
[JsonSerializable(typeof(InstanceUser))]
[JsonSerializable(typeof(ItemComment))]
[JsonSerializable(typeof(ItemCommentsResponse))]
[JsonSerializable(typeof(ItemState))]
[JsonSerializable(typeof(Locale))]
[JsonSerializable(typeof(LocalesResponse))]
[JsonSerializable(typeof(Notification))]
[JsonSerializable(typeof(NotificationTypes))]
[JsonSerializable(typeof(NumRangeFilter))]
[JsonSerializable(typeof(PageDynamic))]
[JsonSerializable(typeof(PageHistory))]
[JsonSerializable(typeof(PageHistoryResponse))]
[JsonSerializable(typeof(PageItem))]
[JsonSerializable(typeof(PageItemProperties))]
[JsonSerializable(typeof(PageItemTemplateType))]
[JsonSerializable(typeof(PageModel))]
[JsonSerializable(typeof(PageModule))]
[JsonSerializable(typeof(PageScripts))]
[JsonSerializable(typeof(PageVisible))]
[JsonSerializable(typeof(PersonalAccessTokenCreationResponse))]
[JsonSerializable(typeof(PersonalAccessTokenListResponse))]
[JsonSerializable(typeof(PersonalAccessTokenRequest))]
[JsonSerializable(typeof(PersonalAccessTokenResponse))]
[JsonSerializable(typeof(PersonalAccessTokenUpdateRequest))]
[JsonSerializable(typeof(PlatformExtension))]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(SeoProperties))]
[JsonSerializable(typeof(ServerUser))]
[JsonSerializable(typeof(SharedModule))]
[JsonSerializable(typeof(Sitemap))]
[JsonSerializable(typeof(SitemapItem))]
[JsonSerializable(typeof(SortOrder))]
[JsonSerializable(typeof(SyncMode))]
[JsonSerializable(typeof(SyncStatusResponse))]
[JsonSerializable(typeof(TeamRole))]
[JsonSerializable(typeof(TeamWithRoles))]
[JsonSerializable(typeof(TokenResponseData))]
[JsonSerializable(typeof(TranslateContentListRequest))]
[JsonSerializable(typeof(TranslateContentRequest))]
[JsonSerializable(typeof(TranslatePageRequest))]
[JsonSerializable(typeof(UrlRedirection))]
[JsonSerializable(typeof(UrlRedirectionDeleteResult))]
[JsonSerializable(typeof(UrlRedirectionItemResult))]
[JsonSerializable(typeof(UrlRedirectionSaveResult))]
[JsonSerializable(typeof(Webhook))]
[JsonSerializable(typeof(WebhookContinuationListing))]
[JsonSerializable(typeof(WebhookHistory))]
[JsonSerializable(typeof(WebhookHistoryContinuationListing))]
[JsonSerializable(typeof(WebsiteListing))]
[JsonSerializable(typeof(WebsiteUser))]
[JsonSerializable(typeof(WorkflowOperationType))]
internal sealed partial class ManagementJsonContext : JsonSerializerContext;
